<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skipped="0" tests="9" time="2.520"><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="10" name="test_noAuthenticated" time="0.611"></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="14" name="test_authenticated" time="0.132"></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="18" name="test_register" time="0.276"></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="28" name="test_register_no_user_name" time="0.143"></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="38" name="test_register_no_user_password" time="0.139"></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="48" name="test_login" time="0.277"><system-out>Here
cesar
</system-out></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="55" name="test_login_wrong_username" time="0.252"><system-out>Here
</system-out></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="62" name="test_login_wrong_password" time="0.262"><system-out>Here
</system-out></testcase><testcase classname="Test.test_Account.TestAccount" file="Test/test_Account.py" line="69" name="test_login_wrong_credentials" time="0.262"><system-out>Here
</system-out></testcase></testsuite>